# The Docker image that will be used to build your app
image: node:lts

stages:
  - deploy

pages:
  stage: deploy
  script:
    - mkdir public
    - rsync -av --exclude='public' . public
  artifacts:
    paths:
      - public
  only:
    - main
